[package]
name = "subsocial-sdk"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
subxt = { version = "0.14", package = "substrate-subxt" }
codec = { package = "parity-scale-codec", version = "1.3.4", features = ["derive", "full"] }

# Pallets
# Substrate dependencies
frame-support = { default-features = false, version = '2.0.1' }
frame-system = { default-features = false, version = '2.0.1' }
pallet-timestamp = { default-features = false, version = '2.0.1' }
sp-std = { default-features = false, version = '2.0.1' }

[dev-dependencies]
async-std = { version = "1.8", features = ["attributes"] }
